# Generated by Django 4.2.20 on 2025-04-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('cpu', models.FloatField()),
                ('memory', models.FloatField()),
                ('parent_pid', models.IntegerField(blank=True, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
